myblog/book/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views
# from django.contrib.staticfiles.urls import static
from django.conf import settings
from django.conf.urls.static import static



from django.contrib import admin
from django.contrib.sitemaps import Sitemap
from django.contrib.sitemaps.views import sitemap
from django.shortcuts import resolve_url
from django.urls import path, include
from .models import Book
import datetime


app_name='book'

class PostSitemap(Sitemap):
    changefreq = "never"
    priority = 0.5

    def items(self):
        return Book.objects.all()

    def location(self, obj):
        data_info=(obj.post_day).strftime("%Y-%m-%d")
        # data_info= obj.post_day
        return resolve_url('book:book_info', data_info=data_info)

    def lastmod(self, obj):
        return obj.post_day

sitemaps = {
    'posts': PostSitemap,
}


urlpatterns = [
    path('', views.TopView.as_view(), name="top"),
    path('quasar/', views.TopquasarView.as_view(), name="top_quasar"),

    path('categorys/', views.CategoryView.as_view(), name='category'),# 本のカテゴリー
    path('categorys/<slug:data_info>', views.CategoryView.as_view(), name='category_info'),

    path('authors/', views.AuthorView.as_view(), name='author'), # 著者について全般
    path('authors/<data_info>', views.AuthorView.as_view(), name='author_info'),

    path('publishers/', views.PublisherView.as_view(), name='publisher'), # 出版社情報
    path('publishers/<slug:data_info>', views.PublisherView.as_view(), name='publisher_info'),

    path('series/', views.SeriesView.as_view(), name='series'), # シリーズもの本
    path('series/<slug:data_info>', views.SeriesView.as_view(), name='series_info'), 

    path('books/', views.BookView.as_view(), name='book'), # 主に本の検索と
    path('books/<slug:data_info>', views.BookView.as_view(), name='book_info'), 

    path('search', views.SearchView.as_view(), name='search' ), # 本の検索全般

    path('articles/', views.ArticlesView.as_view(), name='article'), # トピックスに近いもの

    path('others/', views.OthersView.as_view(),  name='other'),
    path('others/shedule', views.Schedule.as_view(),  name='schedule'),


    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps},  name='sitemap'),

    path('test/', views.test_,  name='test_'),
    
    # path('base', views.TestView.as_view(), name="base"),


    ]





""" 予定-----------------------------
top
    -Recently （最近の投稿）
    -auther（著者）一覧のみ[（あいうえお順）/（男・女）/（年齢）]
        -著者の情報　＋　Book[カテゴリー/出版日]
    -Publisher（出版社）一覧のみ
        -出版社の情報　＋　Author[（あいうえお順）/（男・女）/（年齢）]
    -category（カテゴリー）
    -読む予定の本一覧
    -外部リンク[アリクイちゃんねる/技術コンテンツ/ヨウヘイ]

search
    -カテゴリー
    -出版社
    -著者
    -日付

-----------------------------"""

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include











urlpatterns = [
    path('admin/', admin.site.urls),
    path('book/', include('book.urls')),

]

myblog/book/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models.aggregates import Count
from django.db.models.enums import Choices
from django.db.models.fields import SmallIntegerField, TimeField
from django.db.models.fields.related import ForeignKey
from django.db.models.fields.reverse_related import ManyToOneRel
from django.core.validators import MinLengthValidator, RegexValidator


# いらないｰｰｰｰｰｰｰｰ
# sex_ = (
#     ("man", '男性'),
#     ("woman", '女性')
# )
# ｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰ

# Create your models here.

class Book(models.Model):
    isbn13 = models.CharField(max_length=14,
                                validators=[MinLengthValidator(14, '文字数が一致していません。例）978-4167174033'),
                                            RegexValidator(r'[0-9]{3}[-][0-9]{10}', '形式に当てはまっていません。例）978-4167174033')], null=True, blank=True)

    title = models.CharField('タイトル', max_length=100, null=True, blank=True)
    pages = models.SmallIntegerField('ページ数', null=True, blank=True)
    issue = models.DateField('発行日', null=True, blank=True) # [発行日, y m d]

    post_day = models.DateField('投稿日', null=True, blank=True) # [投稿日, y m d]
    update_day = models.DateField('更新日', null=True, blank=True) # [投稿日, y m d]


    YOUTH_CHOICES = (('Y', 'Youth'),('O', 'Old'))
    youth_choices = models.CharField('青春/白秋', choices=YOUTH_CHOICES, max_length=10)

    series_info = models.ForeignKey("Series", verbose_name=("シリーズ情報"), on_delete=models.CASCADE, null=True, blank=True)
    author_info = models.ForeignKey("Author", verbose_name=("著者情報"), on_delete=models.CASCADE, null=True, blank=True)
    # category_info = models.ManyToManyField("Category", verbose_name=("カテゴリー情報"), blank=True, related_name="category_info")
    category_info = models.ForeignKey("Category", verbose_name=("カテゴリー情報"), blank=True,null=True,on_delete=models.CASCADE)

    publisher_info = models.ForeignKey("Publisher", verbose_name=("出版社情報"), on_delete=models.CASCADE, null=True, blank=True)
    publisher_label_info = models.ForeignKey("Publisher_label", verbose_name=("レーベル"), on_delete=models.CASCADE, null=True, blank=True)

    contents = models.TextField("コンテンツ", null=True, blank=True)
    contents_synopsis =  models.TextField("あらすじ", null=True, blank=True)

    fin = models.BooleanField('完読', null=True, blank=True)

    amazon_url = models.CharField('アマゾンURL', max_length=1000, null=True, blank=True)
    def __str__(self):
        return self.title



class Author(models.Model):
    GENDER_CHOICES = (('Mon', '男性'),('Womon', '女性'))
    WORD_CHOICES = (('Aa', 'あ行'),('Ka', 'か行'),('Sa', 'さ行'),('Ta', 'た行'),('Na', 'な行'),('Ha', 'は行'),('Ma', 'ま行'),('Ya', 'や行'),('Ra', 'ら行'),('Wa', 'わ行'))

    author = models.CharField('著者', max_length=100, default=None) # 追加していく-----------
    author_eng = models.CharField('著者eng', max_length=100) # 追加していく-----------
    word_oder = models.CharField('五十音', choices=WORD_CHOICES, max_length=10)
    age = models.DateField('生年月日')
    sex = models.CharField('性別', choices=(('', '未選択'),)+GENDER_CHOICES, max_length=10, blank=True)
    contents = models.TextField("コンテンツ")
    contents_lite = models.TextField("コンテンツ", blank=True, null=True)

    post_day = models.DateField('投稿日', null=True) # [発行日, y m d]
    def __str__(self):
        return self.author
    
class Category(models.Model):
    CATEGORY_CHOICES = (('action', 'アクション'),('adventure', 'アドベンチャー'),('youth', '青春'),('love', '恋愛'),('sf', 'SF'),('history', '時代'),('mystery', 'ミステリー'),('comedy', 'コメディー'), ('horror', 'ホラー'))
    CATEGORYENG_CHOICES = (('action_eng', 'action'), ('adventure_eng', 'adventure'), ('youth_eng', 'youth'), ('love_eng', 'love'), ('sf_eng', 'sf'), ('history_eng', 'history'), ('mystery_eng', 'mystery'), ('comedy_eng', 'comedy'), ('horror_eng', 'horror'))
    # CATEGORYENG_CHOICES = (('action', 'アクション'),('adventure', 'アドベンチャー'),('youth', '青春'),('love', '恋愛'),('sf', 'SF'),('history', '時代'),('mystery', 'ミステリー'),('comedy', 'コメディー'), ('horror', 'ホラー'))
    COLOR_CHOICES = (('red', 'red'), ('orange','orange'),('blue', 'blue'), ('pink', 'pink'),('info','info'), ('green', 'green'), ('purple', 'purple'), ('warning','warning'),('dark', 'dark'))

    category = models.CharField("カテゴリー", choices=CATEGORY_CHOICES, max_length=20, default=None) # 追加していく-----------
    category_eng = models.CharField("カテゴリーeng", choices=CATEGORYENG_CHOICES ,max_length=20, null=True, blank=True) # 追加していく-----------
    color = models.CharField("色", choices=COLOR_CHOICES, max_length=20)
    color_hex = models.CharField("色_hex値", max_length=20,  blank=True)

    contents = models.TextField("コンテンツ", blank=True)
    contents_keyword = models.TextField("キーワード", blank=True)

    post_day = models.DateField('投稿日', null=True) # [発行日, y m d]
    def __str__(self):
        return self.category

class Publisher(models.Model):
    publisher = models.CharField('出版社', max_length=50)
    publisher_eng = models.CharField('出版社_eng', max_length=50, blank=True, null=True)
    contents = models.TextField("コンテンツ")
    incorporated = models.DateField('設立日')

    post_day = models.DateField('投稿日', null=True) # [発行日, y m d]
    def __str__(self):
        return self.publisher

class Publisher_label(models.Model):
    publisher = models.ForeignKey("Publisher", verbose_name=("出版者"), on_delete=models.CASCADE, null=True, blank=True)
    label = models.CharField("ラベル", max_length=20, default=None) # 追加していく-----------
    label_eng = models.CharField("ラベルeng", max_length=20, default=None) # 追加していく-----------
    def __str__(self):
        return self.label

class Series(models.Model):
    series = models.CharField("シリーズ", max_length=100)
    contents = models.TextField("コンテンツ")

    author = models.ForeignKey("Author", verbose_name=("著者"), on_delete=models.CASCADE)

    post_day = models.DateField('投稿日', null=True) # [発行日, y m d]
    def __str__(self):
        return self.series

class Templates(models.Model):
    breadcrumb = models.TextField("目次")
    










class Departments(models.Model):
    DepartmentId = models.AutoField(primary_key=True)
    DepartmentName = models.CharField(max_length=500)

class Employees(models.Model):
    EmployeeId = models.AutoField(primary_key=True)
    EmployeeName = models.CharField(max_length=500)
    Department = models.CharField(max_length=500)
    DateOfJoining = models.DateField()
    PhotoFileName = models.CharField(max_length=500)







""" 予定 ----------------------------
作品タイトル
出版日
・y
・m
・d
ページ数
画像
感想（コンテンツ）


アマゾンリンク

■集英社
■カテゴリー
　※複数あり
■著者
・男/女
・生まれ年
・
----------------------------"""

myblog/book/forms.py
#django.forms.ModelFormを継承する場合
from django.forms import widgets
from .models import Book, Category, Author, Publisher
from django import forms
from django.shortcuts import render
from django.views.generic import ListView, DetailView, FormView
from django.views.generic.edit import ModelFormMixin, UpdateView
from django.http import Http404
from django.db.models import Prefetch
# from . import forms
# from betterforms.multiform import MultiModelForm
from django.db.models import Q
import datetime

MONTHS = {}
for i in range(1,12):
    MONTHS[i] = i


class BookForm(forms.ModelForm):

    pages_low = forms.IntegerField(label='[本] ページ数', required=False,
        widget=forms.TextInput(attrs={
            'id': 'pages_low',
            'placeholder':'0',
            'pattern':'^[0-9]+$'}))

    pages_high = forms.IntegerField(label="～", label_suffix = " ", required=False,
        widget=forms.TextInput(attrs={
            'id': 'pages_high',
            'placeholder':'500',
            'pattern':'^[0-9]+$',}))

    issue_low = forms.IntegerField(label='[本] 発行日', required=True, initial="1900-1-1",
        widget=forms.SelectDateWidget(empty_label=None, months=MONTHS, years=[x for x in range(1900, datetime.date.today().year+1)], attrs={
            'id': 'issue_low',
            'pattern':'^[0-9]+$',
            'class':'fs-6_5'
        }))

    issue_high = forms.IntegerField(label="～", label_suffix = " ", required=True, initial=datetime.date.today(),
        widget=forms.SelectDateWidget(empty_label=None , months=MONTHS, years=[x for x in range(1900, datetime.date.today().year+1)], attrs={
            'id': 'issue_high',
            'pattern':'^[0-9]+$',
            'class':'fs-6_5'
        }))

    def __init__(self, *args, **kwd):
        super(BookForm, self).__init__(*args, **kwd)
        self.fields["title"].required = False
        self.fields["title"].label = "[本] タイトル"
        self.fields["title"].initial = ""
        
        

        self.label_suffix = " "
        self.labels = None



    class Meta:
        model = Book
        fields = ('title',)
        widgets = {
            'title'   : forms.TextInput(attrs={'placeholder': '虹を待つ彼女'}),
        }
class CategoryForm(forms.ModelForm):
    def __init__(self, *args, **kwd):
        super(CategoryForm, self).__init__(*args, **kwd)
        self.fields["category"].required = False
        self.fields["category"].label = "[本] カテゴリー"
        self.label_suffix = " "
        # self.fields['category'].empty_label = '未選択'
    
    class Meta:
        model = Category
        fields = ('category',)
        widgets = {
            "category": forms.CheckboxSelectMultiple(attrs={'class': 'd-inline-block form-inline mb-2'})
            }


class AuthorForm(forms.ModelForm):
    age_low = forms.IntegerField(label="[著者] 生年月日",  required=True, initial="1900-1-1",
        widget=forms.SelectDateWidget(empty_label=None, months=MONTHS, years=[x for x in range(1900, datetime.date.today().year+1)], attrs={
            'id': 'age_low',
            'class':'fs-6_5'
            }))
    
    age_high = forms.IntegerField(label="～", label_suffix = " ", required=True, initial=datetime.date.today(),
        widget=forms.SelectDateWidget(empty_label=None, months=MONTHS, years=[x for x in range(1900, datetime.date.today().year+1)], attrs={
            'id': 'age_high',
            'class':'fs-6_5'
            }))

    def __init__(self, *args, **kwd):
        super(AuthorForm, self).__init__(*args, **kwd)
        self.fields["author"].required = False
        self.fields["sex"].required = False
        self.fields['sex'].empty_label = '未選択'
        # self.fields["sex"].help_text = "0以上120以下"
        self.fields["sex"].label="[著者] 性別"
        self.fields["author"].label="[著者] 名前"
        self.label_suffix = " "
        self.fields['sex'].choices.insert(0, ('','-----a----' ) )
        
        
    class Meta:
        model = Author
        fields = ('author', 'sex')
        widgets = {
            "sex": forms.RadioSelect(attrs={'placeholder': '[著者] 性別', 'class': 'form-inline'}),
            'author'   : forms.TextInput(attrs={'placeholder': '逸木裕'}),
        }

class PublisherForm(forms.ModelForm):
    choices=[(i.publisher_eng, i.publisher) for i in Publisher.objects.all()]
    publisher = forms.MultipleChoiceField(choices=choices, widget=forms.CheckboxSelectMultiple(attrs={'class': 'd-inline-block form-inline mb-2'}))

    def __init__(self, *args, **kwd):
        super(PublisherForm, self).__init__(*args, **kwd)
        self.fields["publisher"].required = False
        self.fields["publisher"].label = "[出版社] 出版社"
        self.label_suffix = " "
        # self.fields['category'].empty_label = '未選択'
    
    class Meta:
        model = Publisher
        fields = ('publisher',)
        
        # widgets = {
        #     "publisher": forms.CheckboxSelectMultiple(attrs={'class': 'd-inline-block form-inline mb-2'})
        #     }
        # widgets = {
        #     'title': forms.TextInput(attrs={'class': 'textinputclass'}),
        #     'text': forms.Textarea(attrs={'class': 'editable'})
        #     # cssクラスの追加(titleにtextinputclass, textにeditableクラスが追加されるようになります)
        # }



        # self.initial = None
        # self.fields['issue'].queryset = Publisher.objects
        # self.fields["category_info"].required = forms.CheckboxSelectMultiple()
        # self.fields["publisher_info"].required = False
        # self.fields['pages'].required = False
        # self.fields['issue'].required = False

        # validators=[validators.RegexValidator(
        #     regex=u'^[ぁ-んァ-ヶー一-龠]+\u3000[ぁ-んァ-ヶー一-龠]+$',
        #     message='氏名は漢字・ひらがな・カタカナのみとし、氏と名の間に全角スペースを入れてください',
        # )



# self.fields['category_id'].empty_label = '未選択'

        # widgets = {
        #             "name": forms.TextInput(attrs={'placeholder':'紀伊　太郎'}),
        #             "age": forms.RadioSelect(),

        #           }


        # author_age = Author(instance='age')
        # self.fields['author_age'] = author_age

# class UserProfileMultiForm(forms.MultiModelForm):
#     form_classes = {
#         'user': UserForm,
#         'profile': ProfileForm,
#     }




# class CategoryForm(forms.ModelForm):

#     def __init__(self, *args, **kwd):
#         super(CategoryForm, self).__init__(*args, **kwd)
#         self.fields["contents"].required = False

#     class Meta:
#         model = Category
#         fields = ("contents",)
#         widgets = {
#             'contents': forms.Textarea(attrs={'rows':15, 'cols':60}),
        # }




# #django.forms.ModelFormを継承する場合
# from .models import Manage, Category, Member
# from django import forms

# class VideosearchFrom(forms.ModelForm):

#     def __init__(self, *args, **kwd):
#         super(VideosearchFrom, self).__init__(*args, **kwd)
#         self.fields["youtube_video_title"].required = False
#         self.fields["category_id"].required = False
#         # self.fields["youtube_video_episode"].required = False
#         # self.fields["youtube_video_day"].required = False
#         self.fields["members"].required = False
#         self.fields['category_id'].empty_label = '未選択'
#         self.fields['members'].widget = forms.CheckboxSelectMultiple()  # 引数にattrs={'class': 'form-control'}も勿論できる。
#         self.fields['members'].queryset = Member.objects
#         # self.fields['members'].widget.attrs["class"] = "checkbox-inline radio-inline w-100"

#     class Meta:
#         model = Manage
#         # fields = ('youtube_video_title','category_id','youtube_video_episode','youtube_video_day','members') 
#         fields = ('youtube_video_title','category_id','members') 

# class CategoryForm(forms.ModelForm):

#     def __init__(self, *args, **kwd):
#         super(CategoryForm, self).__init__(*args, **kwd)
#         self.fields["contents"].required = False

#     class Meta:
#         model = Category
#         fields = ("contents",)
#         widgets = {
#             'contents': forms.Textarea(attrs={'rows':15, 'cols':60}),
#         }

myblog/book/templates/book/authors_err.html
あいうえお

myblog/book/templates/book/books.html
<!DOCTYPE html>
<html>

<!-- head -->
{% include 'book/head.html' %}




<body>
  <div id="app" class>
    <v-app id="inspire" class="my-bg-color">
      
      <!-- toolbar -->
      {% include 'book/toolbar.html' %}


        
          <!-- 目次 -->

          <v-container class="my-16">
            <v-row
              no-gutters
            >
            <v-col
                cols="12"
                align-self="center"
                class="mx-auto"
              >
            <p class="text-h2 my-text-color-title text-h5 text-md-h4" style="letter-spacing:3px;">
              <v-icon size="40" >mdi-book-open-page-variant</v-icon>
          
              目次</p>
          </v-col>
          
          {% with ''|center:3 as range %}
          {% for _ in range %}
            <v-col
                cols="10"
                align-self="center"
                class="mx-auto mb-14"
              >
              <v-card
              elevation="15"
            >
            
          
              <v-card
                class="mx-auto"
                {% comment %} max-width="344" {% endcomment %}
              >
                <v-img
                {% comment %} src="https://cdn.vuetifyjs.com/images/cards/sunshine.jpg" {% endcomment %}
                {% comment %} src={{ book_list.1.amazon_url | safe }} {% endcomment %}
                {% comment %} height="200px" {% endcomment %}
                >{{ book_list.1.amazon_url | safe }}</v-img>
            
          
                <v-card-text class="pb-0 my-text-color">
                  {{ book_list.1.post_day | safe }}
                </v-card-text>
          
          
                <v-card-title class="pb-0 pt-1">
                  {{ book_list.1.title | safe }}
                </v-card-title>
          
                <v-card-text class="ms-2">
                  <v-icon color="#9A9" size="14">mdi-eye</v-icon>
                  <a class="ms-1 me-3 text-subtitle-2 text-md-subtitle-1 my-text-color-glay">XXX,XXX,XXX</a>
                </v-card-text>
          
                
                <v-card-actions>
                  <v-btn color="{% for item2 in book_list.1.category_info.all %}{{item2.color_hex}}{%endfor%}" elevation="1" outlined rounded small>
                    <form class="d-inline-block" action="{% url 'book:book' %}" method="post">{% csrf_token %}
                      <input type="submit" href="{% url "book:book" %}" value="{% for item2 in book_list.1.category_info.all %}{{item2.get_category_display}}{%endfor%}">
                    </form>
                  </v-btn>
          
          
                  <v-btn color="#455045" elevation="1" outlined rounded small>
                    <form class="d-inline-block" action="{% url 'book:book' %}" method="post">{% csrf_token %}
                      <input type="submit" href="{% url "book:book" %}" value="{{ book_list.1.Author_info }}">
                    </form>
                  </v-btn>
                  <v-btn color="#455045" elevation="1" outlined rounded small>
                    <form class="d-inline-block" action="{% url 'book:book' %}" method="post">{% csrf_token %}
                      <input type="submit" href="{% url "book:book" %}" value="{{ book_list.1.publisher_info}}">
                    </form>
                  </v-btn>
                </v-card-actions>
                <v-card-text>
                  {{ book_list.1.contents_synopsis}}
                </v-card-text>
          
                <v-spacer></v-spacer>
            
          
          
                <v-card-actions>
                  <v-btn color="#1aa179" text class="flex-child-right" href ="{% url 'book:book_info' book_list.1.post_day %}">
                  この記事を読む
                </v-btn>
                </v-card-actions>
          
          
                {% comment %} 
            
                <v-expand-transition>
                  <div v-show="show">
                    <v-divider></v-divider>
            
          
                  </div>
                </v-expand-transition> {% endcomment %}
              </v-card>
            </v-col>
            {% endfor %}
            {% endwith %}          
          
          </v-row>
          </v-container>

















        

</v-row>
</v-container>


  



<!-- footer -->
{% include 'book/footer.html' %}



  
    </div>
  





  </v-app>
  


<!-- sumple あああああ -->  
{% comment %} 


    {% with ''|center:100 as range %}
    {% for _ in range %}
  
    <p>ああ</p>
  
  
  
    {% endfor %}
    {% endwith %}
{% endcomment %}






 
</body>





<!-- components-->
{% include 'book/components.html' %}


<!-- script -->
{% include 'book/script.html' %}

<!-- style -->
{% include 'book/style.html' %}






</html>

myblog/book/templates/book/categorys_err.html
あいうえお

myblog/book/templates/book/contents_subtitle.html
<div id="{{ty}}" class="mx-auto px-0 pt-15 pb-10 text-center">
    <a class="text-my-text-color my-contents-sub-title text-h5 text-md-h4">
        {{text}}
    </a>
</div>

myblog/book/templates/book/footer.html
<v-footer
padless
dark
class="my-bg-color-glay"
>
<v-card
  flat
  tile
  class="lighten-1 white--text text-center my-bg-color-glay my-text-color-light-glay"
  style="width: 100%"
>




<div class="px-6 pt-10 my-text-color-light-glay">
  <v-card-title class="pa-0 pb-1">
    カテゴリー
  </v-card-title>
  <v-card-text class="pl-3 pt-0" style="text-align: left;">
    {% for item in category %}
    <v-btn color="{{item.color_hex}}" class="ma-1" elevation="1" outlined rounded small>
      <form class="d-inline-block" action="{% url 'book:book' %}" method="post">{% csrf_token %}
        <input type="submit" href="{% url "book:book" %}" value="{{item.get_category_display}}">
      </form>
    </v-btn>
    {% endfor %}
  </v-card-text>
</div>




<div class="px-6 pt-4 ">
  <v-card-title class="pa-0 pb-1">
    著者
  </v-card-title>
  <v-card-text class="pl-3 pt-0" style="text-align: left;">
    {% for item in author_Aa %}
    {% for item2 in item %}
      {% if forloop.first %}
      <div class="me-auto mb-2 mb-lg-0 text-start mt-1">
        <a class="text-decoration-none text-start btn-light text-dark fs-6 fs-md-5 rounded d-inline-block">{{item2.get_word_oder_display}}</a>
      {% endif %}


        <v-btn color="{{item.color_hex}}" class="ma-1" elevation="1" outlined rounded small>
          <form class="d-inline-block fs-5_5" action="{% url 'book:book' %}" method="post">{% csrf_token %}<input type="hidden" name="author" value={{ item2.author }}><input type="hidden" name="age_low" value='1900-1-1'><input type="hidden" name="age_high" value={{ date_now|date:"Y-n-j" }}><input type="submit" class="text-decoration-none py-0 px-01 my-1 d-inline-block px-01 py-0 border rounded btn-dark" href="{% url "book:book" %}" value="{{ item2.author }}"></form>
        </v-btn>
        {% if forloop.last %}
        </div>
        {% endif %}
      {% endfor %}
    {% endfor %}
      </v-card-text>
</div>





<div class="px-6 pt-4 ">
  <v-card-title class="pa-0 pb-1">
  出版社
</v-card-title>
<v-card-text class="pl-3 pt-0" style="text-align: left;">
  <v-card-text class="pl-3 pt-0" style="text-align: left;">
    {% for item in publisher %}
    <v-btn color="{{item.color_hex}}" class="ma-1" elevation="1" outlined rounded small>
      <form class="text-decoration-none py-0 px-01 my-1 d-inline-block fs-5_5" action="{% url 'book:book' %}" method="post">{% csrf_token %}<input type="hidden" name="publisher" value={{ item.publisher_eng}}><input type="submit" class="text-decoration-none py-0 px-01 my-1 d-inline-block px-01 py-0 border rounded btn-dark" href="{% url "book:book" %}" value="{{ item.publisher}}"></form>

    </v-btn>
    {% endfor %}
  </v-card-text>
</div>








  {% comment %} <v-card-text class="white--text pt-8">
    Phasellus feugiat arcu sapien, et iaculis ipsum elementum sit amet. Mauris cursus commodo interdum. Praesent ut risus eget metus luctus accumsan id ultrices nunc. Sed at orci sed massa consectetur dignissim a sit amet dui. Duis commodo vitae velit et faucibus. Morbi vehicula lacinia malesuada. Nulla placerat augue vel ipsum ultrices, cursus iaculis dui sollicitudin. Vestibulum eu ipsum vel diam elementum tempor vel ut orci. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
  </v-card-text> {% endcomment %}

  <v-card-text class="my-text-color-light"  style="text-align:right;">

    <v-btn icon fab xlarge dark class="mx-0 my-text-color-light-glay" href="https://twitter.com/BOOK_IC">
      <v-icon size="24" >mdi-twitter</v-icon>
    </v-btn>
    <v-btn icon fab xlarge dark class="mx-0 my-text-color-light-glay" href="https://www.instagram.com/BOOK_I.C/">
      <v-icon size="24" >mdi-instagram</v-icon>
    </v-btn>
</v-card-text>

  <v-divider></v-divider>

  <v-card-text class="my-text-color-light">
    2022 — <strong>Vuetify</strong>
      

  </v-card-text>
</v-card>
</v-footer>